// const data = [
//   {
//     book_id: 1,
//     title: "The Silent Patient",
//     author: "Alex Michaelides",
//     genre: "Thriller",
//     description:
//       "A psychological thriller about a woman who stops speaking after a crime.",
//     price: 14.99,
//     stock_quantity: 120,
//     ISBN: "9781250301697",
//     trending: true,
//     bestseller: true,
//     publisher: "Celadon Books",
//   },
//   {
//     book_id: 2,
//     title: "Where the Crawdads Sing",
//     author: "Delia Owens",
//     genre: "Mystery",
//     description:
//       "A tale of survival, love, and mystery set in the marshes of North Carolina.",
//     price: 12.99,
//     stock_quantity: 95,
//     ISBN: "9780735219106",
//     trending: true,
//     bestseller: true,
//     publisher: "G.P. Putnam's Sons",
//   },
//   {
//     book_id: 3,
//     title: "Atomic Habits",
//     author: "James Clear",
//     genre: "Self-Help",
//     description: "A guide on building good habits and breaking bad ones.",
//     price: 16.99,
//     stock_quantity: 200,
//     ISBN: "9780735211292",
//     trending: true,
//     bestseller: true,
//     publisher: "Avery",
//   },
//   {
//     book_id: 4,
//     title: "Dune",
//     author: "Frank Herbert",
//     genre: "Sci-Fi",
//     description:
//       "An epic story of politics, religion, and power on the desert planet Arrakis.",
//     price: 10.99,
//     stock_quantity: 85,
//     ISBN: "9780441013593",
//     trending: true,
//     bestseller: true,
//     publisher: "Ace Books",
//   },
//   {
//     book_id: 5,
//     title: "Educated",
//     author: "Tara Westover",
//     genre: "Memoir",
//     description:
//       "A memoir about a woman who grows up isolated and later seeks education.",
//     price: 15.99,
//     stock_quantity: 50,
//     ISBN: "9780399590504",
//     trending: false,
//     bestseller: true,
//     publisher: "Random House",
//   },
//   {
//     book_id: 6,
//     title: "Circe",
//     author: "Madeline Miller",
//     genre: "Fantasy",
//     description:
//       "A retelling of the life of the Greek goddess Circe with a feminist twist.",
//     price: 13.99,
//     stock_quantity: 70,
//     ISBN: "9780316556347",
//     trending: true,
//     bestseller: true,
//     publisher: "Little, Brown and Co.",
//   },
//   {
//     book_id: 7,
//     title: "The Alchemist",
//     author: "Paulo Coelho",
//     genre: "Fiction",
//     description: "A fable about following your dreams and personal legend.",
//     price: 11.99,
//     stock_quantity: 150,
//     ISBN: "9780062315007",
//     trending: true,
//     bestseller: true,
//     publisher: "HarperOne",
//   },
//   {
//     book_id: 8,
//     title: "Becoming",
//     author: "Michelle Obama",
//     genre: "Biography",
//     description: "The memoir of former First Lady Michelle Obama.",
//     price: 17.99,
//     stock_quantity: 40,
//     ISBN: "9781524763138",
//     trending: false,
//     bestseller: true,
//     publisher: "Crown Publishing",
//   },
//   {
//     book_id: 9,
//     title: "The Midnight Library",
//     author: "Matt Haig",
//     genre: "Fiction",
//     description:
//       "A story about infinite possibilities and choosing the right path in life.",
//     price: 13.49,
//     stock_quantity: 65,
//     ISBN: "9780525559474",
//     trending: true,
//     bestseller: true,
//     publisher: "Viking",
//   },
//   {
//     book_id: 10,
//     title: "Sapiens: A Brief History of Humankind",
//     author: "Yuval Noah Harari",
//     genre: "History",
//     description:
//       "An exploration of the history and impact of Homo sapiens on Earth.",
//     price: 18.99,
//     stock_quantity: 110,
//     ISBN: "9780062316097",
//     trending: true,
//     bestseller: true,
//     publisher: "Harper",
//   },
// ];

// export default data;
